version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      deps:
        applies-to: version-updates
        patterns:
          - "*"
