spring:
  application:
    name: loom-webflux
  cache:
    caffeine:
      spec: expireAfterWrite=1h
  datasource:
    hikari:
      connectionTimeout: 60000
      maximumPoolSize: 500
      registerMbeans: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off
    lazy-initialization: true
  threads:
    virtual:
      enabled: true

server:
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health, shutdown"
  endpoint:
    shutdown:
      enabled: true

loom-webflux:
  repo-read-only: true
  jvm-metrics-csv-path: bin/jvm.csv
  web-client:
    max-connections: 65000
    connect-timeout: 20s
    pending-acquire-timeout: 60s
    pending-acquire-max-count: ${loom-webflux.web-client.max-connections}
    response-timeout: ${loom-webflux.web-client.pending-acquire-timeout}


